export default {
  nav: {
    home: "Home",
    about: "About",
    services: "Services",
    contact: "Contact",
    login: "Login",
    dashboard: "My Space",
    contactUs: "Contact Us",
  },
  hero: {
    badge: "International Group",
    title1: "Thunderfam",
    title2: "Group Limited",
    tagline: "An international group of stature, rooted in the",
    taglineUK: "United Kingdom",
    taglineAnd: "and",
    taglineCI: "Côte d'Ivoire",
    taglineEnd: ", delivering excellence across every sector since 2018.",
    discoverServices: "Discover our services",
    contactUs: "Contact us",
    stats: {
      countries: "Countries",
      countriesSub: "UK · Côte d'Ivoire",
      founded: "Founded in",
      foundedSub: "United Kingdom",
      sectors: "Sectors",
      sectorsSub: "of activity",
    },
    scrollLabel: "Discover",
  },
  about: {
    badge: "Our Identity",
    title: "About the Group",
    description: "Thunderfam Group Limited is an international group founded in the United Kingdom in 2018, with an active presence in Côte d'Ivoire since 2024. Our ambition: to deliver excellence across a wide range of strategic sectors.",
    mission: "Building bridges between continents, creating value for our clients and contributing to the economic development of the territories where we operate.",
    missionAuthor: "— The mission of Thunderfam Group Limited",
    ukBadge: "Headquarters",
    ciBadge: "Subsidiary",
    companyNumber: "Company Number",
    rccm: "RCCM No.",
    incorporated: "Incorporation Date",
    address: "Address",
    phone: "Phone",
    phone1: "Phone 1",
    phone2: "Phone 2",
    commercialName: "Trade Name",
  },
  services: {
    badge: "Our Domains",
    title: "Our Services",
    description: "Thunderfam Group Limited operates in",
    descriptionBold: "12 strategic sectors",
    descriptionEnd: ", offering a comprehensive range of services tailored to the needs of businesses and individuals across Europe and Africa.",
    included: "Included Services",
    requestQuote: "Request a quote for this service",
  },
  contact: {
    badge: "Let's Talk",
    title: "Contact Us",
    description: "Our team is available to answer all your questions and support you in your projects.",
    offices: "Our Offices",
    officesDesc: "Thunderfam Group Limited is present on two continents to serve you better.",
    emailLabel: "General Email",
    form: {
      title: "Send us a message",
      name: "Full Name",
      namePlaceholder: "Your name",
      email: "Email Address",
      emailPlaceholder: "your@email.com",
      message: "Message",
      messagePlaceholder: "How can we help you?",
      send: "Send Message",
      sending: "Sending...",
      successTitle: "Message sent!",
      successDesc: "Thank you for your message. Our team will get back to you as soon as possible.",
      sendAnother: "Send another message",
      errors: {
        name: "Name is required.",
        email: "Email is required.",
        emailInvalid: "Invalid email address.",
        message: "Message is required.",
      },
    },
  },
  footer: {
    description: "An international group of excellence, present in the United Kingdom and Côte d'Ivoire.",
    quickLinks: "Quick Links",
    ourServices: "Our Services",
    contactInfo: "Contact Info",
    rights: "All rights reserved.",
    legalUK: "Company registered in England and Wales",
    legalCI: "Registered at the RCCM of Abidjan",
    backToTop: "Back to top",
  },
  auth: {
    loginTitle: "Sign In",
    registerTitle: "Create Account",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    fullName: "Full Name",
    loginBtn: "Sign In",
    registerBtn: "Sign Up",
    orContinueWith: "Or continue with",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    signUp: "Sign Up",
    signIn: "Sign In",
    googleLogin: "Continue with Google",
    facebookLogin: "Continue with Facebook",
    appleLogin: "Continue with Apple",
    forgotPassword: "Forgot password?",
  },
  common: {
    loading: "Loading...",
    error: "An error occurred",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    view: "View",
    close: "Close",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    previous: "Previous",
    search: "Search",
    filter: "Filter",
    export: "Export",
    import: "Import",
    upload: "Upload",
    download: "Download",
    submit: "Submit",
    reset: "Reset",
    yes: "Yes",
    no: "No",
    status: {
      active: "Active",
      inactive: "Inactive",
      pending: "Pending",
      completed: "Completed",
      cancelled: "Cancelled",
      inProgress: "In Progress",
    },
  },
  dashboard: {
    welcome: "Welcome",
    myProjects: "My Projects",
    activeProjects: "Active Projects",
    completedProjects: "Completed Projects",
    pendingPayments: "Pending Payments",
    recentActivity: "Recent Activity",
    noProjects: "No projects yet",
    startProject: "Start a Project",
    selectService: "Select a Service",
    myDocuments: "My Documents",
    myInvoices: "My Invoices",
    myTickets: "My Tickets",
    notifications: "Notifications",
  },
  admin: {
    title: "Administration",
    users: "Users",
    projects: "Projects",
    payments: "Payments",
    services: "Services",
    invoices: "Invoices",
    quotes: "Quotes",
    notifications: "Notifications",
    analytics: "Analytics",
    auditLogs: "Audit Logs",
    settings: "Settings",
    assignManager: "Assign Project Manager",
    generateReport: "Generate Report",
  },
  payment: {
    title: "Payment",
    selectMethod: "Choose a payment method",
    fullPayment: "Full Payment",
    fullPaymentDesc: "Pay 100% now",
    installments: "Pay in 3 installments",
    installmentsDesc: "3 equal monthly payments, no fees",
    stripe: "Credit/Debit Card (Stripe)",
    orangeMoney: "Orange Money",
    mtnMoney: "MTN Mobile Money",
    moovMoney: "Moov Money",
    wave: "Wave",
    djamo: "Djamo",
    total: "Total",
    perInstallment: "per installment",
    pay: "Pay",
    success: "Payment Successful",
    failed: "Payment Failed",
  },
};
