export default {
  nav: {
    home: "Inicio",
    about: "Acerca de",
    services: "Servicios",
    contact: "Contacto",
    login: "Iniciar sesión",
    dashboard: "Mi espacio",
    contactUs: "Contáctenos",
  },
  hero: {
    badge: "Grupo Internacional",
    title1: "Thunderfam",
    title2: "Group Limited",
    tagline: "Un grupo internacional de envergadura, arraigado en el",
    taglineUK: "Reino Unido",
    taglineAnd: "y en",
    taglineCI: "Costa de Marfil",
    taglineEnd: ", llevando la excelencia en cada sector de actividad desde 2018.",
    discoverServices: "Descubrir nuestros servicios",
    contactUs: "Contáctenos",
    stats: {
      countries: "Países",
      countriesSub: "UK · Costa de Marfil",
      founded: "Fundado en",
      foundedSub: "Reino Unido",
      sectors: "Sectores",
      sectorsSub: "de actividad",
    },
    scrollLabel: "Descubrir",
  },
  about: {
    badge: "Nuestra identidad",
    title: "Acerca del grupo",
    description: "Thunderfam Group Limited es un grupo internacional fundado en el Reino Unido en 2018, con presencia activa en Costa de Marfil desde 2024. Nuestra ambición: ofrecer servicios de excelencia en una multitud de sectores estratégicos.",
    mission: "Construir puentes entre continentes, crear valor para nuestros clientes y contribuir al desarrollo económico de los territorios donde operamos.",
    missionAuthor: "— La misión de Thunderfam Group Limited",
    ukBadge: "Sede central",
    ciBadge: "Sucursal",
    companyNumber: "Número de empresa",
    rccm: "N° RCCM",
    incorporated: "Fecha de constitución",
    address: "Dirección",
    phone: "Teléfono",
    phone1: "Teléfono 1",
    phone2: "Teléfono 2",
    commercialName: "Nombre comercial",
  },
  services: {
    badge: "Nuestros dominios",
    title: "Nuestros servicios",
    description: "Thunderfam Group Limited opera en",
    descriptionBold: "12 sectores estratégicos",
    descriptionEnd: ", ofreciendo una gama completa de servicios adaptados a las necesidades de empresas y particulares en Europa y África.",
    included: "Servicios incluidos",
    requestQuote: "Solicitar presupuesto para este servicio",
  },
  contact: {
    badge: "Hablemos",
    title: "Contáctenos",
    description: "Nuestro equipo está disponible para responder todas sus preguntas y acompañarle en sus proyectos.",
    offices: "Nuestras oficinas",
    officesDesc: "Thunderfam Group Limited está presente en dos continentes para servirle mejor.",
    emailLabel: "Correo general",
    form: {
      title: "Envíenos un mensaje",
      name: "Nombre completo",
      namePlaceholder: "Su nombre",
      email: "Correo electrónico",
      emailPlaceholder: "su@correo.com",
      message: "Mensaje",
      messagePlaceholder: "¿Cómo podemos ayudarle?",
      send: "Enviar mensaje",
      sending: "Enviando...",
      successTitle: "¡Mensaje enviado!",
      successDesc: "Gracias por su mensaje. Nuestro equipo le responderá a la brevedad posible.",
      sendAnother: "Enviar otro mensaje",
      errors: {
        name: "El nombre es obligatorio.",
        email: "El correo es obligatorio.",
        emailInvalid: "Dirección de correo no válida.",
        message: "El mensaje es obligatorio.",
      },
    },
  },
  footer: {
    description: "Grupo internacional de excelencia, presente en el Reino Unido y Costa de Marfil.",
    quickLinks: "Enlaces rápidos",
    ourServices: "Nuestros servicios",
    contactInfo: "Información de contacto",
    rights: "Todos los derechos reservados.",
    legalUK: "Empresa registrada en Inglaterra y Gales",
    legalCI: "Registrada en el RCCM de Abiyán",
    backToTop: "Volver arriba",
  },
  auth: {
    loginTitle: "Iniciar sesión",
    registerTitle: "Crear cuenta",
    email: "Correo electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    fullName: "Nombre completo",
    loginBtn: "Iniciar sesión",
    registerBtn: "Registrarse",
    orContinueWith: "O continuar con",
    noAccount: "¿No tiene cuenta?",
    hasAccount: "¿Ya tiene cuenta?",
    signUp: "Registrarse",
    signIn: "Iniciar sesión",
    googleLogin: "Continuar con Google",
    facebookLogin: "Continuar con Facebook",
    appleLogin: "Continuar con Apple",
    forgotPassword: "¿Olvidó su contraseña?",
  },
  common: {
    loading: "Cargando...",
    error: "Ocurrió un error",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    view: "Ver",
    close: "Cerrar",
    confirm: "Confirmar",
    back: "Atrás",
    next: "Siguiente",
    previous: "Anterior",
    search: "Buscar",
    filter: "Filtrar",
    export: "Exportar",
    import: "Importar",
    upload: "Subir",
    download: "Descargar",
    submit: "Enviar",
    reset: "Restablecer",
    yes: "Sí",
    no: "No",
    status: {
      active: "Activo",
      inactive: "Inactivo",
      pending: "Pendiente",
      completed: "Completado",
      cancelled: "Cancelado",
      inProgress: "En progreso",
    },
  },
  dashboard: {
    welcome: "Bienvenido",
    myProjects: "Mis proyectos",
    activeProjects: "Proyectos activos",
    completedProjects: "Proyectos completados",
    pendingPayments: "Pagos pendientes",
    recentActivity: "Actividad reciente",
    noProjects: "Sin proyectos por el momento",
    startProject: "Iniciar un proyecto",
    selectService: "Seleccionar un servicio",
    myDocuments: "Mis documentos",
    myInvoices: "Mis facturas",
    myTickets: "Mis tickets",
    notifications: "Notificaciones",
  },
  admin: {
    title: "Administración",
    users: "Usuarios",
    projects: "Proyectos",
    payments: "Pagos",
    services: "Servicios",
    invoices: "Facturas",
    quotes: "Presupuestos",
    notifications: "Notificaciones",
    analytics: "Analíticas",
    auditLogs: "Registros de auditoría",
    settings: "Configuración",
    assignManager: "Asignar jefe de proyecto",
    generateReport: "Generar informe",
  },
  payment: {
    title: "Pago",
    selectMethod: "Elegir método de pago",
    fullPayment: "Pago completo",
    fullPaymentDesc: "Pague el 100% ahora",
    installments: "Pago en 3 cuotas",
    installmentsDesc: "3 cuotas mensuales iguales sin cargos",
    stripe: "Tarjeta bancaria (Stripe)",
    orangeMoney: "Orange Money",
    mtnMoney: "MTN Mobile Money",
    moovMoney: "Moov Money",
    wave: "Wave",
    djamo: "Djamo",
    total: "Total",
    perInstallment: "por cuota",
    pay: "Pagar",
    success: "Pago exitoso",
    failed: "Pago fallido",
  },
};
