export default {
  nav: {
    home: "Accueil",
    about: "À propos",
    services: "Services",
    contact: "Contact",
    login: "Connexion",
    dashboard: "Mon espace",
    contactUs: "Nous contacter",
  },
  hero: {
    badge: "Groupe International",
    title1: "Thunderfam",
    title2: "Group Limited",
    tagline: "Un groupe international d'envergure, ancré au",
    taglineUK: "Royaume-Uni",
    taglineAnd: "et en",
    taglineCI: "Côte d'Ivoire",
    taglineEnd: ", portant l'excellence dans chaque secteur d'activité depuis 2018.",
    discoverServices: "Découvrir nos services",
    contactUs: "Nous contacter",
    stats: {
      countries: "Pays",
      countriesSub: "UK · Côte d'Ivoire",
      founded: "Fondé en",
      foundedSub: "Royaume-Uni",
      sectors: "Secteurs",
      sectorsSub: "d'activité",
    },
    scrollLabel: "Découvrir",
  },
  about: {
    badge: "Notre identité",
    title: "À propos du groupe",
    description: "Thunderfam Group Limited est un groupe international fondé au Royaume-Uni en 2018, avec une présence active en Côte d'Ivoire depuis 2024. Notre ambition : offrir des services d'excellence à travers une multitude de secteurs stratégiques.",
    mission: "Bâtir des ponts entre les continents, créer de la valeur pour nos clients et contribuer au développement économique des territoires où nous opérons.",
    missionAuthor: "— La mission de Thunderfam Group Limited",
    ukBadge: "Siège social",
    ciBadge: "Succursale",
    companyNumber: "Numéro d'entreprise",
    rccm: "N° RCCM",
    incorporated: "Date d'incorporation",
    address: "Adresse",
    phone: "Téléphone",
    phone1: "Téléphone 1",
    phone2: "Téléphone 2",
    commercialName: "Sigle commercial",
  },
  services: {
    badge: "Nos domaines",
    title: "Nos services",
    description: "Thunderfam Group Limited intervient dans",
    descriptionBold: "12 secteurs stratégiques",
    descriptionEnd: ", offrant une gamme complète de services adaptés aux besoins des entreprises et des particuliers en Europe et en Afrique.",
    included: "Prestations incluses",
    requestQuote: "Demander un devis pour ce service",
  },
  contact: {
    badge: "Échangeons",
    title: "Nous contacter",
    description: "Notre équipe est disponible pour répondre à toutes vos questions et vous accompagner dans vos projets.",
    offices: "Nos bureaux",
    officesDesc: "Thunderfam Group Limited est présent sur deux continents pour vous servir au mieux.",
    emailLabel: "Email général",
    form: {
      title: "Envoyez-nous un message",
      name: "Nom complet",
      namePlaceholder: "Votre nom",
      email: "Adresse email",
      emailPlaceholder: "votre@email.com",
      message: "Message",
      messagePlaceholder: "Comment pouvons-nous vous aider ?",
      send: "Envoyer le message",
      sending: "Envoi en cours...",
      successTitle: "Message envoyé !",
      successDesc: "Merci pour votre message. Notre équipe vous répondra dans les plus brefs délais.",
      sendAnother: "Envoyer un autre message",
      errors: {
        name: "Le nom est requis.",
        email: "L'email est requis.",
        emailInvalid: "Adresse email invalide.",
        message: "Le message est requis.",
      },
    },
  },
  footer: {
    description: "Groupe international d'excellence, présent au Royaume-Uni et en Côte d'Ivoire.",
    quickLinks: "Liens rapides",
    ourServices: "Nos services",
    contactInfo: "Coordonnées",
    rights: "Tous droits réservés.",
    legalUK: "Société immatriculée en Angleterre et au Pays de Galles",
    legalCI: "Immatriculée au RCCM d'Abidjan",
    backToTop: "Retour en haut",
  },
  auth: {
    loginTitle: "Connexion",
    registerTitle: "Créer un compte",
    email: "Email",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    fullName: "Nom complet",
    loginBtn: "Se connecter",
    registerBtn: "S'inscrire",
    orContinueWith: "Ou continuer avec",
    noAccount: "Pas encore de compte ?",
    hasAccount: "Déjà un compte ?",
    signUp: "S'inscrire",
    signIn: "Se connecter",
    googleLogin: "Continuer avec Google",
    facebookLogin: "Continuer avec Facebook",
    appleLogin: "Continuer avec Apple",
    forgotPassword: "Mot de passe oublié ?",
  },
  common: {
    loading: "Chargement...",
    error: "Une erreur est survenue",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    view: "Voir",
    close: "Fermer",
    confirm: "Confirmer",
    back: "Retour",
    next: "Suivant",
    previous: "Précédent",
    search: "Rechercher",
    filter: "Filtrer",
    export: "Exporter",
    import: "Importer",
    upload: "Téléverser",
    download: "Télécharger",
    submit: "Soumettre",
    reset: "Réinitialiser",
    yes: "Oui",
    no: "Non",
    status: {
      active: "Actif",
      inactive: "Inactif",
      pending: "En attente",
      completed: "Terminé",
      cancelled: "Annulé",
      inProgress: "En cours",
    },
  },
  dashboard: {
    welcome: "Bienvenue",
    myProjects: "Mes projets",
    activeProjects: "Projets actifs",
    completedProjects: "Projets terminés",
    pendingPayments: "Paiements en attente",
    recentActivity: "Activité récente",
    noProjects: "Aucun projet pour le moment",
    startProject: "Démarrer un projet",
    selectService: "Sélectionner un service",
    myDocuments: "Mes documents",
    myInvoices: "Mes factures",
    myTickets: "Mes tickets",
    notifications: "Notifications",
  },
  admin: {
    title: "Administration",
    users: "Utilisateurs",
    projects: "Projets",
    payments: "Paiements",
    services: "Services",
    invoices: "Factures",
    quotes: "Devis",
    notifications: "Notifications",
    analytics: "Analytics",
    auditLogs: "Journal d'audit",
    settings: "Paramètres",
    assignManager: "Assigner un chef de projet",
    generateReport: "Générer un rapport",
  },
  payment: {
    title: "Paiement",
    selectMethod: "Choisir un mode de paiement",
    fullPayment: "Paiement intégral",
    fullPaymentDesc: "Payez 100% maintenant",
    installments: "Paiement en 3 fois",
    installmentsDesc: "3 mensualités égales sans frais",
    stripe: "Carte bancaire (Stripe)",
    orangeMoney: "Orange Money",
    mtnMoney: "MTN Mobile Money",
    moovMoney: "Moov Money",
    wave: "Wave",
    djamo: "Djamo",
    total: "Total",
    perInstallment: "par mensualité",
    pay: "Payer",
    success: "Paiement réussi",
    failed: "Paiement échoué",
  },
};
